---
layout: post
title: Motivation
---

I want to help expand the world of virtual art during my lifetime. As an advocate of art and sciences, I would love the opportunity to help bridge the gap between real-world interactions and virtual interactions in the future. Whether that be through hardware such as Virtual Reality equipment or software like Metaverse worlds, my goal is to have both tech-savvy and non-tech-savvy people enjoy life experiences through tech. I have yet to determine all the challenges that will come about from wanting to develop new tools/software for this field. However, I am very enthusiastic that my life experiences will carry me to the places I need to be to make those things happen.
I always let my grandfather know first, when I have achieved something new. Whether it be academical or things that I learn in my personal life, I always look to him for guidance. When I reach a point of higher success in the future, he will be the first to know, and the first to make sure I get there as well. Going forward from there, I will speak with my mom and dad, as well as all the other people in my life that made sure I get to the point I reach. Without others, I would have never reached the success I have had, in my career and in my life. To reach the goals that I have set for myself now, I will work hard everyday to make sure I can continue to do what I like to do, surrounded by those that support me, now and into the future.
As a project that I could potentially contribute to, I took a look at [Google’s AR Core](https://developers.google.com/ar/develop) open source project, which launched back in 2018. It is a platform for building augmented reality experiences using numerous different APIs. In essence, it enables your phone to sense its environment, understand the world and interact with virtual information in augmented reality, according to Google's AR Core website overview. The project spans across the platforms of IOS and Android, which I am very familiar with. Having said that, I believe it is a project I could see myself contributing to, as they have active Github forums working on issues for both platforms, with their most recent posts being that of two days ago. Not only that, but the project has extensive documentation, and is sponsored by many other corporations. In turn, it gives me the sense that this project is here to stay for some time in the future, and is a place where my contributions can live for the next few years if I decide to contribute.


![ Motivation ](https://images.unsplash.com/photo-1548438294-1ad5d5f4f063?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2344&q=80)
